---
- hosts: localhost
  gather_facts: no
  vars:
    - heat_environment_file: "my-heat-params.yml"
  tasks:
    - name: Build a Heat stack for Etherpad
      register: heat_stack
      os_stack:
        name: "etherpad-stack"
        state: present
        template: "../files/etherpad-heat-stack.yml"
        environment:
          - "{{ heat_environment_file }}"

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Add Galera nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[etherpad_network_name][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
      when: item.addresses[etherpad_network_name]|length == 1

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Add Etherpad frontend node to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[etherpad_network_name][1].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
      when: item.addresses[etherpad_network_name]|length == 2

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Generate an inventory file
      template: src=templates/etherpad_inventory.j2 dest=../etherpad_inventory

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for the Etherpad frontend node to become accessible
      wait_for:
        host: "{{ hostvars[groups['etherpad'][0]]['ansible_ssh_host'] }}"
        port: 22
        state: started

- hosts: galera
  gather_facts: no
  tasks:
    - name: Wait for the Galera cluster nodes to become accessible
      wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 22
        state: started
      delegate_to: etherpad_node
