---
- hosts: etherpad
  become: yes
  tasks:
    - name: Install ansible-role-pip dependencies
      package:
        name:
          - wget
          - python3
          - python-is-python3

- hosts: etherpad
  become: yes
  roles:
    - ansible-role-pip
    - ansible-role-docker
    - role: etherpad-galera-haproxy
      nodes:
        - name: "{{ hostvars[groups['galera'][0]]['inventory_hostname'] }}"
          address: "{{ hostvars[groups['galera'][0]]['ansible_ssh_host'] }}"
        - name: "{{ hostvars[groups['galera'][1]]['inventory_hostname'] }}"
          address: "{{ hostvars[groups['galera'][1]]['ansible_ssh_host'] }}"
        - name: "{{ hostvars[groups['galera'][2]]['inventory_hostname'] }}"
          address: "{{ hostvars[groups['galera'][2]]['ansible_ssh_host'] }}"
    - ansible-role-nodejs

- hosts: etherpad
  remote_user: "{{ vm_user_account }}"
  roles:
    - role: etherpad
      mysql_password: "{{ lookup('password', 'credentials/mysql_pw length=15') }}"
